version: '3'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "5033:6379"
    networks:
      - my-network
    command: redis-server

  mysql:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_news
    ports:
      - "5022:3306"
    networks:
      - my-network

networks:
  my-network:
